### ISSUE TITLE
Any future support for RabbitMq?

### ISSUE THREAD

**Issue by zerai** [gpslab/domain-event#11]

**Comment by peter-gribanov** [comment]
Good question.
It was planned to add support for RabbitMq, but there was no way to test it.
Are you using RabbitMq? Can you check RabbitMq support?

**Comment by zerai** [comment]
I'm not an expert, but maybe [this](https://github.com/phpinnacle/ridge) implementation/code can be useful look travis.yml and test folder.
This lib is wrapped/used even in [php-service-bus](https://github.com/php-service-bus/service-bus)
what do you think?

**Comment by peter-gribanov** [comment]
Thanks for the links.

**Comment by peter-gribanov** [comment]
Now you can use RabbitMQ.
See guide for more details:
https://github.com/gpslab/domain-event/blob/master/docs/queue/subscribe/amqp.md
